### PR TITLE
feat: add support for `log-console-output`

### PR DESCRIPTION
**Pull request by marrws**
This settings allows to specify a different format for the log output. currently keycloak supports `default` and `json`.

ref: https://www.keycloak.org/server/all-config#_logging

### CODE REVIEW

**Review by vigohe — COMMENTED** [review]
LGTM

**Review by ordenador — APPROVED** [review]
LGTM

**Review by abrahamjoc — COMMENTED** [review]
LGTM!

**Review by rnt — APPROVED** [review]

**Comment by harishdesetti1206** [comment]
LGTM. Seems this is a good change as the log format can be chosen which helps in the monitoring of the application and in slicing and dicing the logs.

**Review by harishdesetti1206 — APPROVED** [review]

**Pull request merged**
